name: Publish to npm and GitHub Packages

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Этап 1: Настройка для NPM ---
      - name: Setup Node.js for npm
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # --- Этап 2: Перенастройка для GitHub Packages ---
      - name: Setup Node.js for GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          # Указываем на реестр GitHub
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          # Используем GITHUB_TOKEN, который теперь будет правильно ассоциирован
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

